### ISSUE TITLE
遇到问题，解决问题，你就会变得越来越优秀，加油！

### ISSUE THREAD

**Issue by lencx** [BovineBeta/AutoRun#1]

**Comment by BovineBeta** [comment]
谢谢你的鼓励!

![谢谢你的鼓励!](https://user-images.githubusercontent.com/83176414/208411462-b582c452-c622-4e58-be72-6f629d41eafa.png)

**Comment by lencx** [comment]
不客气，被你的主页吸引过来的。编程源于生活，不光可以写代码，这个思维模式还可以用来解决生活中的各种问题，学以致用才能融会贯通 😀

**Comment by BovineBeta** [comment]
好的, 谢谢!
